#pragma once

#include <common.h>
#include <swf.h>
#include <objects.h>

typedef void (*action_runtime_func)(SWFAppContext* app_context, ASObject* this, u32 num_args);

typedef enum
{
	STR_ID_EMPTY = 1,
	STR_ID_GLOBAL,
	STR_ID_ROOT,
	STR_ID_PARENT,
	STR_ID_FLASH,
	STR_ID_DISPLAY,
	STR_ID_RECOMP,
	STR_ID_RECOMP_GET_LAST_KEY,
	STR_ID_RECOMP_SET_DISPLAY_SCALE,
	STR_ID_RECOMP_SIN,
	STR_ID_RECOMP_COS,
	STR_ID_RECOMP_COLOR_TRANSFORM,
	STR_ID_RED_MULTIPLIER,
	STR_ID_GREEN_MULTIPLIER,
	STR_ID_BLUE_MULTIPLIER,
	STR_ID_ALPHA_MULTIPLIER,
	STR_ID_RED_OFFSET,
	STR_ID_GREEN_OFFSET,
	STR_ID_BLUE_OFFSET,
	STR_ID_ALPHA_OFFSET,
	STR_ID_OBJECT,
	STR_ID_DESTROY,
	STR_ID_TO_STRING,
	STR_ID_VALUE_OF,
	STR_ID_RECOMP_ID,
	STR_ID_FUNCTION,
	STR_ID_NUMBER,
	STR_ID_STRING,
	STR_ID_ARRAY,
	STR_ID_PUSH,
	STR_ID_POP,
	STR_ID_THIS,
	STR_ID_ARGUMENTS,
	STR_ID_SUPER,
	STR_ID_CONSTRUCTOR,
	STR_ID_PROTOTYPE,
	STR_ID_PROTO,
	STR_ID_LENGTH,
	STR_ID_MOVIECLIP,
	STR_ID__ROTATION,
	STR_ID__X,
	STR_ID__Y,
	STR_ID__XSCALE,
	STR_ID__YSCALE,
	STR_ID_TRANSFORM,
	STR_ID_ATTACH_BITMAP,
	STR_ID_CREATE_EMPTY_MOVIECLIP,
	STR_ID_REMOVE_MOVIECLIP,
	STR_ID_ON_ENTER_FRAME,
	STR_ID_ON_KEY_DOWN,
	STR_ID_ColorTransform,
	STR_ID_BITMAP_DATA,
	STR_ID_colorTransform,
	STR_ID_LOAD_BITMAP,
	STR_ID_WIDTH,
	STR_ID_HEIGHT,
	STR_ID_SOUND,
	STR_ID_LOAD_SOUND,
	STR_ID_ON_LOAD,
	STR_ID_START,
	STR_ID_KEY,
	STR_ID_FIRE_LISTENERS_DOWN,
	STR_ID_FIRE_LISTENERS_UP,
	STR_ID_ASSETPROPFLAGS,
	STR_ID_MATH,
	STR_ID_ABS,
	STR_ID_X,
	STR_ID_Y,
	STR_ID_Z,
	STR_ID_NAN,
	STR_ID_POSITIVE_INFINITY,
	STR_ID_NEGATIVE_INFINITY,
	STR_ID_MAX_VALUE,
	STR_ID_MIN_VALUE,
} StringIds;

typedef struct
{
	u32 object_string_id;
	u32 func_string_id;
	action_runtime_func func;
	bool constructor;
} RuntimeFunc;