#pragma once

#include <stdbool.h>

#include <rb_tree.h>

#include <common.h>
#include <swf.h>

#define RBT_GET_OR_INS(t, s, c) rbtree_get_or_insert(app_context, t, s, c)
#define RBT_GET_OR_INS_U64(t, s) rbtree_get_or_insert_u64(app_context, t, s)
#define RBT_INS_U64(t, s) rbtree_insert_u64(app_context, t, s)

/**
 * Red-Black Tree interface.
 *
 * Wrapper around red-black tree.
 */

typedef struct
{
	struct rb_tree t;
	size_t length;
	size_t struct_size;
} rbtree;

typedef struct
{
	struct rb_node n;
	u32 string_id;
} rbnode;

/**
 * Initialize the tree.
 *
 * @param t Pointer to tree to be inited
 * @param struct_size Size of struct rbnode is in
 */
void rbtree_init(rbtree* t, size_t struct_size);

/**
 * Get a node and return it if it exists, or return NULL if it doesn't.
 *
 * @param t Pointer to "this" rbtree
 * @param string_id Unique integer generated by recompiler id'ing a string
 * @return Pointer to node
 */
rbnode* rbtree_get(rbtree* t, u32 string_id);

/**
 * Get a node that might not exist, or create it if it doesn't.
 *
 * @param app_context Pointer to the app context
 * @param t Pointer to "this" rbtree
 * @param string_id Unique integer generated by recompiler id'ing a string
 * @return Pointer to existing/newly-created node
 */
rbnode* rbtree_get_or_insert(SWFAppContext* app_context, rbtree* t, u32 string_id, bool* created);

/**
 * Get a node and return it if it exists, or return NULL if it doesn't.
 * This function accepts a u64 key
 *
 * @param t Pointer to "this" rbtree
 * @param key Unique integer identifying the node to return
 * @return Pointer to node
 */
void* rbtree_get_u64(rbtree* t, u64 key);

/**
 * Get a node that might not exist, or create it if it doesn't.
 *
 * @param app_context Pointer to the app context
 * @param t Pointer to "this" rbtree
 * @param key Unique integer identifying the node to return
 * @return Pointer to existing/newly-created node
 */
void* rbtree_get_or_insert_u64(SWFAppContext* app_context, rbtree* t, u64 key);

/**
 * Insert a node that may not exist, or do nothing if it does already.
 *
 * @param app_context Pointer to the app context
 * @param t Pointer to "this" rbtree
 * @param key Unique integer identifying the node to insert
 */
void rbtree_insert_u64(SWFAppContext* app_context, rbtree* t, u64 key);

/**
 * Remove a node, or do nothing if it does not exist.
 *
 * @param app_context Pointer to the app context
 * @param t Pointer to "this" rbtree
 * @param key Unique integer identifying the node to remove
 */
void rbtree_remove_u64(SWFAppContext* app_context, rbtree* t, u64 key);

/**
 * Removes the root of the tree and returns it.
 *
 * @param t Pointer to "this" rbtree
 * @return Pointer to root node
 */
void* rbtree_pop_root(rbtree* t);