#pragma once

#include <stdbool.h>

#include <rb_tree.h>

#define RBT_GET_OR_INS(t, s) rbtree_get_or_insert(app_context, t, s)

/**
 * Red-Black Tree interface.
 *
 * Wrapper around red-black tree.
 */

typedef struct
{
	struct rb_tree t;
	size_t struct_size;
} rbtree;

typedef struct
{
	struct rb_node n;
	u32 string_id;
} rbnode;

/**
 * Initialize the tree.
 *
 * @param app_context Main app context
 * @param size Heap size in bytes
 */
void rbtree_init(rbtree* t, size_t struct_size);

/**
 * Get a node and return it if it exists, but return NULL if it doesn't.
 *
 * @param t Pointer to "this" rbtree
 * @param string_id Unique integer generated by recompiler id'ing a string
 * @return Pointer to node
 */
rbnode* rbtree_get(rbtree* t, u32 string_id);

/**
 * Get a node that might not exist, but create it if it doesn't.
 *
 * @param t Pointer to "this" rbtree
 * @param string_id Unique integer generated by recompiler id'ing a string
 * @return Pointer to existing/newly-created node
 */
rbnode* rbtree_get_or_insert(SWFAppContext* app_context, rbtree* t, u32 string_id);